# Generated by Django 2.0.5 on 2018-08-04 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlHitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlKeyHash',
            fields=[
                ('key', models.CharField(db_index=True, max_length=16, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='urlhitlog',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlshortner.UrlKeyHash'),
        ),
    ]
