# Generated by Django 2.0.5 on 2018-08-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlkeyhash',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
