# Generated by Django 2.0.5 on 2018-08-04 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_urlkeyhash_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlkeyhash',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
