# Generated by Django 2.0.5 on 2018-08-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0003_auto_20180804_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlkeyhash',
            name='expired_on',
            field=models.DateField(null=True),
        ),
    ]
